import Head from 'next/head';
import Header from '../src/components/header';
import Layout from '../src/components/layout';
import Banner from "../src/images/codingbg.jpeg"

export default function Home() {
  return (
    <Layout>
      <Head>
        <title>Phung Porfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header 
        title="About"
        content=""
        pageBanner={Banner}
      />
    </Layout>
  );
}
