import Head from 'next/head';
import About from '../src/components/about';
import Banner from '../src/components/banner';
import Layout from '../src/components/layout';
import Technologies from '../src/components/technologies';
import Img from "../src/images/codingbg.jpeg"

export default function Home() {
  return (
    <Layout>
      <Head>
        <title>Phung Porfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta
          property="og:image"
          content={Img}
        />
        <link rel="icon" href="/favicon.ico" />
        <script src="https://unpkg.com/@lottiefiles/lottie-player@latest/dist/lottie-player.js"></script>
      </Head>
      <Banner />
      <About />
      <Technologies />
    </Layout>
  );
}
